name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu:22.03
    steps:
    - name: Linux setup
      run: |
        sudo apt-get install \
          tar \
          autoconf \
          automake \
          autotools-dev \
          autopoint \
          libtool \
          pkg-config
    - name: Configure autotools (Linux, openssl)
      run: |
        cd /tmp
        curl -fSL https://download.strongswan.org/strongswan-5.9.11.tar.bz2 -o strongswan.tar.bz2
        tar xjf strongswan.tar.bz2
        cd strongswan-5.9.11
        autoreconf -i
        CC="gcc"
        CXX="g++"
        ./configure \
          --disable-shared \
          --enable-static \
          --enable-monolithic
        make
    - uses: actions/upload-artifact@v3
      with:
        name: aria2c
        path: /tmp/strongswan-5.9.11
